### ISSUE TITLE
Nettverkssøk etter deltakere funker ikke

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMdeltakere#71]
```
Fatal error: Uncaught Error: Call to a member function setInnslag() on null in /etc/php-includes/UKM/Innslag/Innslag.php:766 Stack trace: 

#0 UKMDesignWordpress/vendor/twig/twig/src/Extension/CoreExtension.php(1531): UKMNorge\Innslag\Innslag->getPersoner() 
#1 UKMDesignWordpress/vendor/twig/twig/src/Environment.php(358) : eval()'d code(180): twig_get_attribute(Object(Twig\Environment), Object(Twig\Source), Object(UKMNorge\Innslag\Innslag), 'getPersoner', Array, 'method', false, false, false, 71) 
#2 UKMDesignWordpress/vendor/twig/twig/src/Template.php(396): __TwigTemplate_a9a4ba820c15f33ecf120953086a9424209099faab790e4a1f01329e488d1ed4->doDisplay(Array, Array) 
#3 UKMDesignWordpress/vendor/twig/twig/src/Template.php(369): Twig\Template->displayWithErrorHandling(Array, Array) 
#4 UKMDesignWordpress/vendor/twig/twig/src/Te in /etc/php-includes/UKM/Innslag/Innslag.php on line 766
```

**Comment by mariusmandal** [comment]
Fixed by 2efe6caf8a95002ec72adcfb25589ae90563ba2a
